<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/images/SN_web_lightmode.png" width="300" alt="cognitiveclass.ai logo">
</center>

# Working with a real world data-set using SQL and Python

Estimated time needed: **30** minutes

## Objectives

After completing this lab you will be able to:

*   Understand the dataset for Chicago Public School level performance
*   Store the dataset in SQLite database.
*   Retrieve metadata about tables and columns and query data from mixed case columns
*   Solve example problems to practice your SQL skills including using built-in database functions

## Chicago Public Schools - Progress Report Cards (2011-2012)

The city of Chicago released a dataset showing all school level performance data used to create School Report Cards for the 2011-2012 school year. The dataset is available from the Chicago Data Portal: [https://data.cityofchicago.org/Education/Chicago-Public-Schools-Progress-Report-Cards-2011-/9xs2-f89t](https://data.cityofchicago.org/Education/Chicago-Public-Schools-Progress-Report-Cards-2011-/9xs2-f89t?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01&cm_mmc=Email_Newsletter-\_-Developer_Ed%2BTech-\_-WW_WW-\_-SkillsNetwork-Courses-IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork-20127838&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ)

This dataset includes a large number of metrics. Start by familiarizing yourself with the types of metrics in the database: [https://data.cityofchicago.org/api/assets/AAD41A13-BE8A-4E67-B1F5-86E711E09D5F?download=true](https://data.cityofchicago.org/api/assets/AAD41A13-BE8A-4E67-B1F5-86E711E09D5F?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01&download=true&cm_mmc=Email_Newsletter-\_-Developer_Ed%2BTech-\_-WW_WW-\_-SkillsNetwork-Courses-IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork-20127838&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ)

**NOTE**:

Do not download the dataset directly from City of Chicago portal. Instead download a static copy which is a more database friendly version from this <a href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoPublicSchools.csv?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01">link</a>.

Now review some of its contents.

### Connect to the database

Let us now load the ipython-sql  extension and establish a connection with the database

##### The syntax for connecting to magic sql using sqllite is

  **%sql sqlite://DatabaseName**   
  
where DatabaseName will be your **.db** file

In [5]:
import csv, sqlite3

con = sqlite3.connect("RealWorldData.db")
cur = con.cursor()

In [6]:

# !pip install -q pandas==1.1.5

In [7]:
%load_ext sql

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [8]:
%sql sqlite:///RealWorldData.db

### Store the dataset in a Table

##### In many cases the dataset to be analyzed is available as a .CSV (comma separated values) file, perhaps on the internet.  
##### To analyze the data using SQL, it first needs to be stored in the database.

##### We will first read the csv files  from the given url  into pandas dataframes

##### Next we will be using the  df.to_sql() function to convert each csv file  to a table in sqlite  with the csv data loaded in it.

In [9]:
# if you have csv file then load it using pandas and convert into sql using to_sql()
import pandas
df = pandas.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoPublicSchools.csv")
df.to_sql("CHICAGO_PUBLIC_SCHOOLS_DATA", con, if_exists='replace', index=False, method="multi")

566

### Query the database system catalog to retrieve table metadata

##### You can verify that the table creation was successful by retrieving the list of all tables in your schema and checking whether the SCHOOLS table was created

In [11]:
# type in your query to retrieve list of all tables in the database
%sql select name from sqlite_master where type='table'

 * sqlite:///RealWorldData.db
Done.

[('CHICAGO_PUBLIC_SCHOOLS_DATA',)]

### Query the database system catalog to retrieve column metadata

##### The SCHOOLS table contains a large number of columns. How many columns does this table have?

In [14]:
# type in your query to retrieve the number of columns in the SCHOOLS table
%sql SELECT count(name) FROM PRAGMA_TABLE_INFO('CHICAGO_PUBLIC_SCHOOLS_DATA');

 * sqlite:///RealWorldData.db
Done.

[(78,)]

Now retrieve the the list of columns in SCHOOLS table and their column type (datatype) and length.

In [16]:
# type in your query to retrieve all column names in the SCHOOLS table along with their datatypes and length
%sql select name, type, length(type) from PRAGMA_TABLE_INFO('CHICAGO_PUBLIC_SCHOOLS_DATA');

 * sqlite:///RealWorldData.db
Done.

[('School_ID', 'INTEGER', 7),
 ('NAME_OF_SCHOOL', 'TEXT', 4),
 ('Elementary, Middle, or High School', 'TEXT', 4),
 ('Street_Address', 'TEXT', 4),
 ('City', 'TEXT', 4),
 ('State', 'TEXT', 4),
 ('ZIP_Code', 'INTEGER', 7),
 ('Phone_Number', 'TEXT', 4),
 ('Link', 'TEXT', 4),
 ('Network_Manager', 'TEXT', 4),
 ('Collaborative_Name', 'TEXT', 4),
 ('Adequate_Yearly_Progress_Made_', 'TEXT', 4),
 ('Track_Schedule', 'TEXT', 4),
 ('CPS_Performance_Policy_Status', 'TEXT', 4),
 ('CPS_Performance_Policy_Level', 'TEXT', 4),
 ('HEALTHY_SCHOOL_CERTIFIED', 'TEXT', 4),
 ('Safety_Icon', 'TEXT', 4),
 ('SAFETY_SCORE', 'REAL', 4),
 ('Family_Involvement_Icon', 'TEXT', 4),
 ('Family_Involvement_Score', 'TEXT', 4),
 ('Environment_Icon', 'TEXT', 4),
 ('Environment_Score', 'REAL', 4),
 ('Instruction_Icon', 'TEXT', 4),
 ('Instruction_Score', 'REAL', 4),
 ('Leaders_Icon', 'TEXT', 4),
 ('Leaders_Score', 'TEXT', 4),
 ('Teachers_Icon', 'TEXT', 4),
 ('Teachers_Score', 'TEXT', 4),
 ('Parent_Engagement_Icon', 'TEXT', 4),
 ('Parent_Engagement_Score', 'TEXT', 4),
 ('Parent_Environment_Icon', 'TEXT', 4),
 ('Parent_Environment_Score', 'TEXT', 4),
 ('AVERAGE_STUDENT_ATTENDANCE', 'TEXT', 4),
 ('Rate_of_Misconducts__per_100_students_', 'REAL', 4),
 ('Average_Teacher_Attendance', 'TEXT', 4),
 ('Individualized_Education_Program_Compliance_Rate', 'TEXT', 4),
 ('Pk_2_Literacy__', 'TEXT', 4),
 ('Pk_2_Math__', 'TEXT', 4),
 ('Gr3_5_Grade_Level_Math__', 'TEXT', 4),
 ('Gr3_5_Grade_Level_Read__', 'TEXT', 4),
 ('Gr3_5_Keep_Pace_Read__', 'TEXT', 4),
 ('Gr3_5_Keep_Pace_Math__', 'TEXT', 4),
 ('Gr6_8_Grade_Level_Math__', 'TEXT', 4),
 ('Gr6_8_Grade_Level_Read__', 'TEXT', 4),
 ('Gr6_8_Keep_Pace_Math_', 'TEXT', 4),
 ('Gr6_8_Keep_Pace_Read__', 'TEXT', 4),
 ('Gr_8_Explore_Math__', 'TEXT', 4),
 ('Gr_8_Explore_Read__', 'TEXT', 4),
 ('ISAT_Exceeding_Math__', 'REAL', 4),
 ('ISAT_Exceeding_Reading__', 'REAL', 4),
 ('ISAT_Value_Add_Math', 'REAL', 4),
 ('ISAT_Value_Add_Read', 'REAL', 4),
 ('ISAT_Value_Add_Color_Math', 'TEXT', 4),
 ('ISAT_Value_Add_Color_Read', 'TEXT', 4),
 ('Students_Taking__Algebra__', 'TEXT', 4),
 ('Students_Passing__Algebra__', 'TEXT', 4),
 ('9th Grade EXPLORE (2009)', 'TEXT', 4),
 ('9th Grade EXPLORE (2010)', 'TEXT', 4),
 ('10th Grade PLAN (2009)', 'TEXT', 4),
 ('10th Grade PLAN (2010)', 'TEXT', 4),
 ('Net_Change_EXPLORE_and_PLAN', 'TEXT', 4),
 ('11th Grade Average ACT (2011)', 'TEXT', 4),
 ('Net_Change_PLAN_and_ACT', 'TEXT', 4),
 ('College_Eligibility__', 'TEXT', 4),
 ('Graduation_Rate__', 'TEXT', 4),
 ('College_Enrollment_Rate__', 'TEXT', 4),
 ('COLLEGE_ENROLLMENT', 'INTEGER', 7),
 ('General_Services_Route', 'INTEGER', 7),
 ('Freshman_on_Track_Rate__', 'TEXT', 4),
 ('X_COORDINATE', 'REAL', 4),
 ('Y_COORDINATE', 'REAL', 4),
 ('Latitude', 'REAL', 4),
 ('Longitude', 'REAL', 4),
 ('COMMUNITY_AREA_NUMBER', 'INTEGER', 7),
 ('COMMUNITY_AREA_NAME', 'TEXT', 4),
 ('Ward', 'INTEGER', 7),
 ('Police_District', 'INTEGER', 7),
 ('Location', 'TEXT', 4)]

### Questions

1.  Is the column name for the "SCHOOL ID" attribute in upper or mixed case?
2.  What is the name of "Community Area Name" column in your table? Does it have spaces?
3.  Are there any columns in whose names the spaces and paranthesis (round brackets) have been replaced by the underscore character "\_"?

## Problems

### Problem 1

##### How many Elementary Schools are in the dataset?

In [17]:
%sql select count(*) from CHICAGO_PUBLIC_SCHOOLS_DATA where "Elementary, Middle, or High School"='ES';

 * sqlite:///RealWorldData.db
Done.

[(462,)]

### Problem 2

##### What is the highest Safety Score?

In [18]:
%sql select * from CHICAGO_PUBLIC_SCHOOLS_DATA limit 3;

 * sqlite:///RealWorldData.db
Done.

[(610038, 'Abraham Lincoln Elementary School', 'ES', '615 W Kemper Pl', 'Chicago', 'IL', 60614, '(773) 534-5720', 'http://schoolreports.cps.edu/SchoolProgressReport_Eng/Spring2011Eng_610038.pdf', 'Fullerton Elementary Network', 'NORTH-NORTHWEST SIDE COLLABORATIVE', 'No', 'Standard', 'Not on Probation', 'Level 1', 'Yes', 'Very Strong', 99.0, 'Very Strong', '99', 'Strong', 74.0, 'Strong', 66.0, 'Weak', '65', 'Strong', '70', 'Strong', '56', 'Average', '47', '96.00%', 2.0, '96.40%', '95.80%', '80.1', '43.3', '89.6', '84.9', '60.7', '62.6', '81.9', '85.2', '52', '62.4', '66.3', '77.9', 69.7, 64.4, 0.2, 0.9, 'Yellow', 'Green', '67.1', '54.5', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 813, 33, 'NDA', 1171699.458, 1915829.428, 41.92449696, -87.64452163, 7, 'LINCOLN PARK', 43, 18, '(41.92449696, -87.64452163)'),
 (610281, 'Adam Clayton Powell Paideia Community Academy Elementary School', 'ES', '7511 S South Shore Dr', 'Chicago', 'IL', 60649, '(773) 535-6650', 'http://schoolreports.cps.edu/SchoolProgressReport_Eng/Spring2011Eng_610281.pdf', 'Skyway Elementary Network', 'SOUTH SIDE COLLABORATIVE', 'No', 'Track_E', 'Not on Probation', 'Level 1', 'No', 'Average', 54.0, 'Strong', '66', 'Strong', 74.0, 'Very Strong', 84.0, 'Weak', '63', 'Strong', '76', 'Weak', '46', 'Average', '50', '95.60%', 15.7, '95.30%', '100.00%', '62.4', '51.7', '21.9', '15.1', '29', '42.8', '38.5', '27.4', '44.8', '42.7', '14.1', '34.4', 16.8, 16.5, 0.7, 1.4, 'Green', 'Green', '17.2', '27.3', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 521, 46, 'NDA', 1196129.985, 1856209.466, 41.76032435, -87.55673627, 43, 'SOUTH SHORE', 7, 4, '(41.76032435, -87.55673627)'),
 (610185, 'Adlai E Stevenson Elementary School', 'ES', '8010 S Kostner Ave', 'Chicago', 'IL', 60652, '(773) 535-2280', 'http://schoolreports.cps.edu/SchoolProgressReport_Eng/Spring2011Eng_610185.pdf', 'Midway Elementary Network', 'SOUTHWEST SIDE COLLABORATIVE', 'No', 'Standard', 'Not on Probation', 'Level 2', 'No', 'Strong', 61.0, 'NDA', 'NDA', 'Average', 50.0, 'Weak', 36.0, 'Weak', 'NDA', 'NDA', 'NDA', 'Average', '47', 'Weak', '41', '95.70%', 2.3, '94.70%', '98.30%', '53.7', '26.6', '38.3', '34.7', '43.7', '57.3', '48.8', '39.2', '46.8', '44', '7.5', '21.9', 18.3, 15.5, -0.9, -1.0, 'Red', 'Red', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 1324, 44, 'NDA', 1148427.165, 1851012.215, 41.74711093, -87.73170248, 70, 'ASHBURN', 13, 8, '(41.74711093, -87.73170248)')]

In [19]:

%sql select MAX(SAFETY_SCORE) from CHICAGO_PUBLIC_SCHOOLS_DATA;

 * sqlite:///RealWorldData.db
Done.

[(99.0,)]

### Problem 3

##### Which schools have highest Safety Score?

In [20]:
%sql select NAME_OF_SCHOOL from CHICAGO_PUBLIC_SCHOOLS_DATA where SAFETY_SCORE = (select max(SAFETY_SCORE) from CHICAGO_PUBLIC_SCHOOLS_DATA);

 * sqlite:///RealWorldData.db
Done.

[('Abraham Lincoln Elementary School',),
 ('Alexander Graham Bell Elementary School',),
 ('Annie Keller Elementary Gifted Magnet School',),
 ('Augustus H Burley Elementary School',),
 ('Edgar Allan Poe Elementary Classical School',),
 ('Edgebrook Elementary School',),
 ('Ellen Mitchell Elementary School',),
 ('James E McDade Elementary Classical School',),
 ('James G Blaine Elementary School',),
 ('LaSalle Elementary Language Academy',),
 ('Mary E Courtenay Elementary Language Arts Center',),
 ('Northside College Preparatory High School',),
 ('Northside Learning Center High School',),
 ('Norwood Park Elementary School',),
 ('Oriole Park Elementary School',),
 ('Sauganash Elementary School',),
 ('Stephen Decatur Classical Elementary School',),
 ('Talman Elementary School',),
 ('Wildwood Elementary School',)]

### Problem 4

##### What are the top 10 schools with the highest "Average Student Attendance"?

In [26]:
%sql select Name_of_School, Average_Student_Attendance from CHICAGO_PUBLIC_SCHOOLS_DATA \
    order by Average_Student_Attendance desc nulls last limit 10

 * sqlite:///RealWorldData.db
Done.

[('John Charles Haines Elementary School', '98.40%'),
 ('James Ward Elementary School', '97.80%'),
 ('Edgar Allan Poe Elementary Classical School', '97.60%'),
 ('Orozco Fine Arts & Sciences Elementary School', '97.60%'),
 ('Rachel Carson Elementary School', '97.60%'),
 ('Annie Keller Elementary Gifted Magnet School', '97.50%'),
 ('Andrew Jackson Elementary Language Academy', '97.40%'),
 ('Lenart Elementary Regional Gifted Center', '97.40%'),
 ('Disney II Magnet School', '97.30%'),
 ('John H Vanderpoel Elementary Magnet School', '97.20%')]

### Problem 5

##### Retrieve the list of 5 Schools with the lowest Average Student Attendance sorted in ascending order based on attendance

In [28]:
%sql select Name_of_School, Average_Student_Attendance from CHICAGO_PUBLIC_SCHOOLS_DATA \
    order by Average_Student_Attendance limit 5;

 * sqlite:///RealWorldData.db
Done.

[('Velma F Thomas Early Childhood Center', None),
 ('Richard T Crane Technical Preparatory High School', '57.90%'),
 ('Barbara Vick Early Childhood & Family Center', '60.90%'),
 ('Dyett High School', '62.50%'),
 ('Wendell Phillips Academy High School', '63.00%')]

### Problem 6

##### Now remove the '%' sign from the above result set for Average Student Attendance column

In [29]:
%sql SELECT Name_of_School, REPLACE(Average_Student_Attendance, '%', '') \
     from CHICAGO_PUBLIC_SCHOOLS_DATA \
     order by Average_Student_Attendance \
     LIMIT 5

 * sqlite:///RealWorldData.db
Done.

[('Velma F Thomas Early Childhood Center', None),
 ('Richard T Crane Technical Preparatory High School', '57.90'),
 ('Barbara Vick Early Childhood & Family Center', '60.90'),
 ('Dyett High School', '62.50'),
 ('Wendell Phillips Academy High School', '63.00')]

### Problem 7

##### Which Schools have Average Student Attendance lower than 70%?

In [33]:
%sql SELECT Name_of_School, Average_Student_Attendance\
     from CHICAGO_PUBLIC_SCHOOLS_DATA \
        WHERE Average_Student_Attendance <70 order by Average_Student_Attendance desc;

 * sqlite:///RealWorldData.db
Done.

[('Roberto Clemente Community Academy High School', '69.60%'),
 ('Chicago Vocational Career Academy High School', '68.80%'),
 ('Manley Career Academy High School', '66.80%'),
 ('Orr Academy High School', '66.30%'),
 ('Wendell Phillips Academy High School', '63.00%'),
 ('Dyett High School', '62.50%'),
 ('Barbara Vick Early Childhood & Family Center', '60.90%'),
 ('Richard T Crane Technical Preparatory High School', '57.90%')]

### Problem 8

##### Get the total College Enrollment for each Community Area

In [34]:
%sql select Community_Area_Name, sum(College_Enrollment) AS TOTAL_ENROLLMENT \
   from CHICAGO_PUBLIC_SCHOOLS_DATA \
   group by Community_Area_Name

 * sqlite:///RealWorldData.db
Done.

[('ALBANY PARK', 6864),
 ('ARCHER HEIGHTS', 4823),
 ('ARMOUR SQUARE', 1458),
 ('ASHBURN', 6483),
 ('AUBURN GRESHAM', 4175),
 ('AUSTIN', 10933),
 ('AVALON PARK', 1522),
 ('AVONDALE', 3640),
 ('BELMONT CRAGIN', 14386),
 ('BEVERLY', 1636),
 ('BRIDGEPORT', 3167),
 ('BRIGHTON PARK', 9647),
 ('BURNSIDE', 549),
 ('CALUMET HEIGHTS', 1568),
 ('CHATHAM', 5042),
 ('CHICAGO LAWN', 7086),
 ('CLEARING', 2085),
 ('DOUGLAS', 4670),
 ('DUNNING', 4568),
 ('EAST GARFIELD PARK', 5337),
 ('EAST SIDE', 5305),
 ('EDGEWATER', 4600),
 ('EDISON PARK', 910),
 ('ENGLEWOOD', 6832),
 ('FOREST GLEN', 1431),
 ('FULLER PARK', 531),
 ('GAGE PARK', 9915),
 ('GARFIELD RIDGE', 4552),
 ('GRAND BOULEVARD', 2809),
 ('GREATER GRAND CROSSING', 4051),
 ('HEGEWISCH', 963),
 ('HERMOSA', 3975),
 ('HUMBOLDT PARK', 8620),
 ('HYDE PARK', 1930),
 ('IRVING PARK', 7764),
 ('JEFFERSON PARK', 1755),
 ('KENWOOD', 4287),
 ('LAKE VIEW', 7055),
 ('LINCOLN PARK', 5615),
 ('LINCOLN SQUARE', 4132),
 ('LOGAN SQUARE', 7351),
 ('LOOP', 871),
 ('LOWER WEST SIDE', 7257),
 ('MCKINLEY PARK', 1552),
 ('MONTCLARE', 1317),
 ('MORGAN PARK', 3271),
 ('MOUNT GREENWOOD', 2091),
 ('NEAR NORTH SIDE', 3362),
 ('NEAR SOUTH SIDE', 1378),
 ('NEAR WEST SIDE', 7975),
 ('NEW CITY', 7922),
 ('NORTH CENTER', 7541),
 ('NORTH LAWNDALE', 5146),
 ('NORTH PARK', 4210),
 ('NORWOOD PARK', 6469),
 ('OAKLAND', 140),
 ('OHARE', 786),
 ('PORTAGE PARK', 6954),
 ('PULLMAN', 1620),
 ('RIVERDALE', 1547),
 ('ROGERS PARK', 4068),
 ('ROSELAND', 7020),
 ('SOUTH CHICAGO', 4043),
 ('SOUTH DEERING', 1859),
 ('SOUTH LAWNDALE', 14793),
 ('SOUTH SHORE', 4543),
 ('UPTOWN', 4388),
 ('WASHINGTON HEIGHTS', 4006),
 ('WASHINGTON PARK', 2648),
 ('WEST ELSDON', 3700),
 ('WEST ENGLEWOOD', 5946),
 ('WEST GARFIELD PARK', 2622),
 ('WEST LAWN', 4207),
 ('WEST PULLMAN', 3240),
 ('WEST RIDGE', 8197),
 ('WEST TOWN', 9429),
 ('WOODLAWN', 4206)]

### Problem 9

##### Get the 5 Community Areas with the least total College Enrollment  sorted in ascending order

In [37]:
%sql select Community_Area_Name, sum(College_Enrollment) AS TOTAL_ENROLLMENT \
   from CHICAGO_PUBLIC_SCHOOLS_DATA \
   group by Community_Area_Name order by TOTAL_ENROLLMENT asc limit 5 ;

 * sqlite:///RealWorldData.db
Done.

[('OAKLAND', 140),
 ('FULLER PARK', 531),
 ('BURNSIDE', 549),
 ('OHARE', 786),
 ('LOOP', 871)]

### Problem 10

##### List 5 schools with lowest safety score.

In [38]:
%sql SELECT name_of_school, safety_score \
FROM CHICAGO_PUBLIC_SCHOOLS_DATA  where safety_score !='None' \
ORDER BY safety_score \
LIMIT 5

 * sqlite:///RealWorldData.db
Done.

[('Edmond Burke Elementary School', 1.0),
 ("Luke O'Toole Elementary School", 5.0),
 ('George W Tilton Elementary School', 6.0),
 ('Foster Park Elementary School', 11.0),
 ('Emil G Hirsch Metropolitan High School', 13.0)]

### Problem 11

##### Get the hardship index for the community area of the school which has College Enrollment of 4368

In [40]:
df = pandas.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoCensusData.csv")
df.to_sql("CENSUS_DATA", con, if_exists='replace', index=False,method="multi")

78

In [41]:

%%sql 
select hardship_index from CENSUS_DATA CD, CHICAGO_PUBLIC_SCHOOLS_DATA CPS 
where CD.community_area_number = CPS.community_area_number 
and college_enrollment = 4368

 * sqlite:///RealWorldData.db
Done.

[(6.0,)]

Double-click **here** for the solution.

<!-- Solution:
NOTE: For this solution to work the CHICAGO_SOCIOECONOMIC_DATA table 
      as created in the last lab of Week 3 should already exist. If the CHICAGO_SOCIOECONOMIC_DATA table does not exists, please execute the following code beforehand.

df = pandas.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoCensusData.csv")
df.to_sql("CENSUS_DATA", con, if_exists='replace', index=False,method="multi")


%%sql 
select hardship_index from CENSUS_DATA CD, CHICAGO_PUBLIC_SCHOOLS_DATA CPS 
where CD.community_area_number = CPS.community_area_number 
and college_enrollment = 4368


-->

### Problem 12

##### Get the hardship index for the community area which has the highest value for College Enrollment

In [42]:
%sql select community_area_number, community_area_name, hardship_index from CENSUS_DATA \
   where community_area_number in \
   ( select community_area_number from CHICAGO_PUBLIC_SCHOOLS_DATA order by college_enrollment desc limit 1 )

 * sqlite:///RealWorldData.db
Done.

[(5.0, 'North Center', 6.0)]

Double-click **here** for the solution.

<!-- Solution:
NOTE: For this solution to work the CHICAGO_SOCIOECONOMIC_DATA table 
      as created in the last lab of Week 3 should already exist. If the CHICAGO_SOCIOECONOMIC_DATA table does not exists, please execute the following code beforehand.

df = pandas.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoCensusData.csv")
df.to_sql("CENSUS_DATA", con, if_exists='replace', index=False,method="multi")

%sql select community_area_number, community_area_name, hardship_index from CENSUS_DATA \
   where community_area_number in \
   ( select community_area_number from CHICAGO_PUBLIC_SCHOOLS_DATA order by college_enrollment desc limit 1 )
-->

## Summary

##### In this lab you learned how to work with a real word dataset using SQL and Python. You learned how to query columns with spaces or special characters in their names and with mixed case names. You also used built in database functions and practiced how to sort, limit, and order result sets, as well as used sub-queries and worked with multiple tables.